config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :sample_sessions
  resources :large_sample_sessions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sample_session.rb
class SampleSession
  attr_accessor :key, :value

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  validates :key, :presence => true
  validates :value, :presence => true

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sample_sessions_controller.rb
class SampleSessionsController < ApplicationController
  def index
    @sample_sessions = session.to_h
    render "index"
  end

  def create
    @sample_session = SampleSession.new(session_params)

    if @sample_session.valid?
      session[@sample_session.key] = @sample_session.value
      redirect_to sample_sessions_path
    else
      render :new
    end
  end

  def new
    @sample_session = SampleSession.new
    render "new"
  end

  def destroy
    session.delete(params[:id])
    redirect_to sample_sessions_path
  end

  private

  def session_params
    params.require(:sample_session).permit(:key, :value)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSessionDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/sample_sessions/_form.html.erb
<%= form_with(model: sample_session, local: true) do |form| %>
  <% if sample_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sample_session.errors.count, "error") %> prohibited this sample_session from being saved:</h2>

      <ul>
        <% sample_session.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <div class="form-group">
      <%= form.label :key %>
      <%= form.text_field :key, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :value %>
      <%= form.text_area :value, class: 'form-control' %>
    </div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sample_sessions/edit.html.erb
<h1>Editing Sample Session</h1>

<%= render 'form', sample_session: @sample_session %>

<%= link_to 'Show', @sample_session %> |
<%= link_to 'Back', sample_sessions_path %>

app/views/sample_sessions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Variables in Rails Session Cookie</h1>

<table class="table">
  <thead>
    <tr>
      <td>Key</td>
      <td colspan="2">Value</td> 
    </tr>
  </thead>

  <tbody>
    <% @sample_sessions.each do |k, v| %>
      <tr>
        <td><%= k %></td>
        <td><%= v %></td> 
        <td><%= link_to "delete", sample_session_path(k), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sample Session', new_sample_session_path %>

app/views/sample_sessions/new.html.erb
<h1>Add key to session</h1>

<%= render 'form', sample_session: @sample_session %>

<%= link_to 'Back', sample_sessions_path %>

app/views/sample_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_sample_session_path(@sample_session) %> |
<%= link_to 'Back', sample_sessions_path %>